export const BRAND_REGISTER_REQUEST = 'BRAND_REGISTER_REQUEST'
export const BRAND_REGISTER_SUCCESS = 'BRAND_REGISTER_SUCCESS'
export const BRAND_REGISTER_FAIL = 'BRAND_REGISTER_FAIL'
export const BRAND_REGISTER_RESET = 'BRAND_REGISTER_RESET'

export const BRAND_UPDATE_REQUEST = 'BRAND_UPDATE_REQUEST'
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS'
export const BRAND_UPDATE_FAIL = 'BRAND_UPDATE_FAIL'
export const BRAND_UPDATE_RESET = 'BRAND_UPDATE_RESET'

export const BRAND_GET_LIST_REQUEST = 'BRAND_GET_LIST_REQUEST'
export const BRAND_GET_LIST_SUCCESS = 'BRAND_GET_LIST_SUCCESS'
export const BRAND_GET_LIST_FAIL = 'BRAND_GET_LIST_FAIL'
export const BRAND_GET_LIST_RESET = 'BRAND_GET_LIST_RESET'

export const BRAND_GET_LIST_BY_CATEGORY_ID_REQUEST = 'BRAND_GET_LIST_BY_CATEGORY_ID_REQUEST'
export const BRAND_GET_LIST_BY_CATEGORY_ID_SUCCESS = 'BRAND_GET_LIST_BY_CATEGORY_ID_SUCCESS'
export const BRAND_GET_LIST_BY_CATEGORY_ID_FAIL = 'BRAND_GET_LIST_BY_CATEGORY_ID_FAIL'
export const BRAND_GET_LIST_BY_CATEGORY_ID_RESET = 'BRAND_GET_LIST_BY_CATEGORY_ID_RESET'

export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST'
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS'
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL'
export const BRAND_DELETE_RESET = 'BRAND_DELETE_RESET'
