export const NOTIFICATIONS_GET_LIST_REQUEST = 'NOTIFICATIONS_GET_LIST_REQUEST'
export const NOTIFICATIONS_GET_LIST_SUCCESS = 'NOTIFICATIONS_GET_LIST_SUCCESS'
export const NOTIFICATIONS_GET_LIST_FAIL = 'NOTIFICATIONS_GET_LIST_FAIL'
export const NOTIFICATIONS_GET_LIST_RESET = 'NOTIFICATIONS_GET_LIST_RESET'

export const NOTIFICATIONS_UPDATE_REQUEST = 'NOTIFICATIONS_UPDATE_REQUEST'
export const NOTIFICATIONS_UPDATE_SUCCESS = 'NOTIFICATIONS_UPDATE_SUCCESS'
export const NOTIFICATIONS_UPDATE_FAIL = 'NOTIFICATIONS_UPDATE_FAIL'
export const NOTIFICATIONS_UPDATE_RESET = 'NOTIFICATIONS_UPDATE_RESET'
